services:
  - docker

before_install:
  - docker image build -t adbushnell/travis_image:v1.0 .

deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"
  - docker image push adbushnell/travis_image:v1.0
