language:
  - generic

services:
  - docker

before_install:
  - docker image build -t adbushnell/travis_image:v1.0 .

before_deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"

deploy:
  provider: script
  script: docker image push adbushnell/travis_image:v1.0
  on:
    branch: main
